# Generated by Django 4.2.1 on 2023-06-02 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acct_number', models.IntegerField()),
                ('merchant_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('yard', models.BooleanField()),
                ('pool', models.BooleanField()),
                ('square_footage', models.IntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeplaceapi.area')),
            ],
        ),
        migrations.CreateModel(
            name='Swapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeplaceapi.area')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeplaceapi.paymenttype')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeplaceapi.property')),
                ('swapper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeplaceapi.swapper')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('review', models.TextField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='homeplaceapi.property')),
                ('swapper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeplaceapi.swapper')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeplaceapi.swapper'),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='swapper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeplaceapi.swapper'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeplaceapi.property')),
                ('swapper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeplaceapi.swapper')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeplaceapi.city'),
        ),
    ]
