# Generated by Django 4.2.1 on 2023-06-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeplaceapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(default=False, max_length=15),
        ),
        migrations.AddField(
            model_name='swapper',
            name='favorites',
            field=models.ManyToManyField(related_name='swapper_favorites', through='homeplaceapi.Favorite', to='homeplaceapi.property'),
        ),
    ]
